### ISSUE TITLE
Can't tap this repo

### ISSUE THREAD

**Issue by kbrock** [robertgzr/homebrew-tap#12]
Can't figure out how to tap this cask

```
brew tap robertgzr/homebrew-tap
==> Tapping robertgzr/tap
Cloning into '/usr/local/Homebrew/Library/Taps/robertgzr/homebrew-tap'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 186 (delta 0), reused 2 (delta 0), pack-reused 183
Receiving objects: 100% (186/186), 43.39 KiB | 2.28 MiB/s, done.
Resolving deltas: 100% (95/95), done.
Error: Invalid cask: /usr/local/Homebrew/Library/Taps/robertgzr/homebrew-tap/Casks/font-iosevka-inziu.rb
Cask 'font-iosevka-inziu' is unreadable: undefined method `method_missing_message' for Utils:Module
Error: Cannot tap robertgzr/tap: invalid syntax in tap!
```

I wasn't able to figure out either what I was doing wrong or what was quirky about this file.

Thanks for providing this great repo

**Comment by robertgzr** [comment]
Thanks for the report.

I removed the cask altogether since it was replaced by the pSarasa Gothic](https://github.com/be5invis/Sarasa-Gothic) project as far as I know.

There's even a cask for it in the official fonts repo: https://github.com/Homebrew/homebrew-cask-fonts/blob/049018c08dccaab9fc7ce237203cdfc87910b69d/Casks/font-sarasa-gothic.rb

**Comment by robertgzr** [comment]
should be fixed by https://github.com/robertgzr/homebrew-tap/commit/15a8045bcbf45b2dd15a4f07e01c170fe5616a49

**Comment by kbrock** [comment]
thanks so much
